name: CI

on:
    pull_request: ~
    push:
        branches:
            - 4.x
        tags:
            - '*'
    schedule:
        - cron: 0 13 * * MON,TUE

jobs:
    security:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.3, 7.4, 8.0]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  tools: prestissimo, flex
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v2

            - name: Install the dependencies
              run: |
                  composer require sensiolabs/security-checker --dev --no-update
                  composer install --no-interaction --no-suggest

            - name: Run the security check
              run: vendor/bin/security-checker security:check --ansi
